### PR TITLE
1.20.6 port

### PR DESCRIPTION
**Pull request by imreallybadatnames**
Entirely untested. Compiles perfectly fine, though. No warnings or errors.

### CODE REVIEW

**Comment by DaFuqs** [comment]
Client Rendering looking good

**Comment by DaFuqs** [comment]
Trying to launch it crashes for me with `de.dafuqs.arrowhead.mixin.LastCrossbowVelocityStore is in a defined mixin package de.dafuqs.arrowhead.mixin.* owned by arrowhead.mixins.json and cannot be referenced directly`.
I guess the interface should be put into a separate package? Mixin usually doesn't like non-mixins in its package.

**Review by DaFuqs — CHANGES_REQUESTED** [review]
`LastCrossbowVelocityStore` IllegalClassLoadError has to be looked into first.

**Comment by imreallybadatnames** [comment]
1.20.6 now.

**Review by DaFuqs — APPROVED** [review]

**Comment by DaFuqs** [comment]
Perfect, thank you!

**Pull request merged**
